<template lang="jade">
  h1 Videa HTML Components and Patterns
  :marked
    - Advanced Insights
    - Autocomplete
    - Avail Detail
    - Avails List
    - Avails Request
    - Button
    - Calendar
    - Card
    - Checkbox
    - Dashboard
    - Date Input
    - Dropdown
    - Email Template
    - Error Template
    - Gallery
    - Glossary
    - Gravatar
    - Icon
    - Login Page
    - Maintenance Template
    - Map
    - Media
    - Multi Select
    - On Track Ratings Indicator
    - Order
    - Order Management
    - Orders
    - Pagination
    - People
    - Price Guide
    - Program Guide
    - Proposal
    - Proposals
    - Range Input
    - Select
    - Site Footer
    - Site Header
    - Site Navigation
    - Sports & Specials
    - Text Input
    - Video
</template>
