import Vue from 'vue'

export default {
  registerAllGlobalComponents () {
    Vue.component('icon', require('components/Icon'))
    Vue.component('panel', require('components/Panel'))
    Vue.component('modal', require('components/Modal'))
    Vue.component('vui-input', require('components/Input'))
    Vue.component('sidebar', require('components/Sidebar'))
    Vue.component('spinner', require('components/Spinner'))
    Vue.component('datepicker', require('components/Datepicker'))
    Vue.component('page-heading', require('components/PageHeading'))
    Vue.component('checkbox-list', require('components/CheckboxList'))
    Vue.component('daypart-selector', require('components/DaypartSelector'))
    Vue.component('data-grid-heading', require('components/DataGridHeading'))
    Vue.component('vui-sorting-column', require('components/SortingColumn'))
    Vue.component('close-button', require('components/CloseButton'))
    Vue.component('resizable-textarea', require('components/ResizableTextarea'))
    Vue.component('page-title', require('components/PageTitle'))
    Vue.component('vui-pager', require('components/Pager'))
    Vue.component('order-details-info', require('components/OrderDetailsInfo'))
    Vue.component('makegoods-total-grid', require('components/MakegoodsTotalGrid'))
    Vue.component('offers-makegoods-classification-dropdown', require('components/OffersMakegoodsClassificationDropdown'))
    Vue.component('makegoods-preempts-grid', require('components/MakegoodsPreemptsGrid'))
    Vue.component('offers-makegoods-common-avail-offer-grids-wrapper', require('components/OffersMakegoodsCommonAvailOfferGridsWrapper'))
    Vue.component('offers-makegoods-requested-dayparts-popup', require('components/OffersMakegoodsRequestedDaypartsPopup'))
    Vue.component('offers-makegood-offered-spots-grid', require('components/OffersMakegoodOfferedSpotsGrid'))
    Vue.component('offers-makegoods-avails-filter', require('components/OffersMakegoodsAvailsFilter'))
    Vue.component('offers-makegoods-avails-grid', require('components/OffersMakegoodsAvailsGrid'))
    Vue.component('makegoods-program-name-change-lines-grid', require('components/MakegoodsProgramNameChangeLinesGrid'))
    Vue.component('makegoods-offer-spots-grid', require('components/MakegoodsOfferSpotsGrid'))
    Vue.component('offer-tab-details', require('components/OfferTabDetails'))
    Vue.component('offer-popup', require('components/OfferPopup'))
    Vue.component('orbit-details-popup', require('components/OrbitDetailsPopup'))
    Vue.component('ebiz-history-grid', require('components/EbizHistoryGrid'))
    Vue.component('revision-history-grid', require('components/RevisionHistoryGrid'))
    Vue.component('vom-spot-allocation-header', require('components/VomSpotAllocationHeader'))
    Vue.component('vom-spot-allocation-with-missed-spots', require('components/VomSpotAllocationWithMissedSpots'))
    Vue.component('nested-order-line-grid', require('components/NestedOrderLineGrid'))
    Vue.component('nested-order-line-invoice-details-grid', require('components/NestedOrderLineInvoiceDetailsGrid'))
    Vue.component('nested-order-line-makegoods-grid', require('components/NestedOrderLineMakegoodsGrid'))
    Vue.component('offers-reject-offer-popup', require('components/OffersRejectOfferPopup'))
    Vue.component('order-line-current-info-popup', require('components/OrderLineCurrentInfoPopup'))
    Vue.component('offer-tab-order-grid', require('components/OfferTabOrderGrid'))
    Vue.component('offer-tab-offer-grid', require('components/OfferTabOfferGrid'))
    Vue.component('orbit-details-popup-grid', require('components/OrbitDetailsPopupGrid'))
    Vue.component('order-line-curr-info-rate-rating-grid', require('components/OrderLineCurrInfoRateRatingGrid'))
    Vue.component('active-orders-filter', require('components/ActiveOrdersFilter'))
    Vue.component('active-orders-grid', require('components/ActiveOrdersGrid'))
    Vue.component('spots-run-not-ordered-popup', require('components/SpotsRunNotOrderedPopup'))
    Vue.component('spots-run-not-ordered-popup', require('components/SpotsRunNotOrderedPopup'))
    Vue.component('orders-details-grid', require('components/OrdersDetailsGrid'))
    Vue.component('orders-details-tabs', require('components/OrdersDetailsTabs'))
    Vue.component('campaign-performance-list-filter', require('components/CampaignPerformanceListFilter'))
    Vue.component('items-per-page-selector', require('components/ItemsPerPageSelector'))
    Vue.component('campaign-performance-list-grid', require('components/CampaignPerformanceListGrid'))
    Vue.component('open-preempts-filter', require('components/OpenPreemptsFilter'))
    Vue.component('open-preempts-grid', require('components/OpenPreemptsGrid'))
    Vue.component('edit-text-field-popup', require('components/EditTextFieldPopup'))
    Vue.component('back-to-top', require('components/BackToTop'))
  }
}
